### ISSUE TITLE
With Nextor call (_RDDRV, 73h)  partitions can't be accesible

### ISSUE THREAD

**Issue by bladeba** [Konamiman/Nextor#10] opened 2018-12-10 16:58 UTC
After a call to read absolute sector (_RDDRV, 73h) in a partitioned device, if you try to search for "Next FIB", the partition won't be accesible anymore...

That doesn't happen with a DISK-IO (4160h) call with the (_CDRVR, 7Bh) Nextor's call.

**Comment by Konamiman** [comment] 2019-01-20 17:21
I can't reproduce this. Can you please send me some example code that causes the bug? Also, what is the disk transfer address when you use this function call?

**Comment by bladeba** [comment] 2019-01-20 17:40
https://github.com/bladeba/MSX/blob/master/Test_routines/prueba_particion.asm

**Comment by Konamiman** [comment] 2019-01-23 14:27
That code works fine for me. I need more details: what is the exact configuration of the system you are using? (hardware, partitions mapping)

**Comment by bladeba** [comment] 2019-01-24 04:30
COnfiguraton:

 - 2 FAT16 partitions  in Nextor 2.1 Alpha 2

 - Tested in real MSX Turbo R with MegaflashROM SD, Rookie Drive,
Flashjacks... and in openMSX emulating MegaflashROM SD

**Comment by Konamiman** [comment] 2019-07-26 07:07
Fixed in v2.1.0 beta 2

**Closed as completed by Konamiman** 2019-07-26 07:07 UTC
Labels: bug, fixplemented
