### ISSUE TITLE
HDDEMU v.1.02~1.04

### ISSUE THREAD

**Issue by gdx-msx** [Konamiman/Nextor#37] opened 2019-11-16 01:57 UTC
Hi,

These versions don't work on disk with partitions created with the Nextor driver.

http://msx.org/forum/msx-talk/software/question-about-hddemu

**Comment by Konamiman** [comment] 2020-07-12 09:39
Nextor's FDISK creates partitions in a pretty standard way, so I'd say that the problem is with HDDEMU itself.

I'm closing this for now, but if you can point some way in which Nextor is incorrectly creating the partitions, or can provide more detailed data on which part of the partition format is HDDEMU unhappy about, I'll be glad to take another look.

**Closed as completed by Konamiman** 2020-07-12 09:39 UTC
