### ISSUE TITLE
Nextor as Master and IDE250.DAT as slave freeze on IDE drive access

### ISSUE THREAD

**Issue by sdsnatcher** [Konamiman/Nextor#8] opened 2018-11-25 13:28 UTC
When an interface with Nextor is used together with an IDE that still has the IDE250.DAT BIOS, the System boots fine. 

But Nextor will freeze on the first access done to a drive of the IDE. It might even be just a DIR command.

DRVINFO shows the correct information, but "DEVINFO 0" shows only the Nextor devices. In my case, not even the TR floppy drive was shown in the list in this case

Tested with Nextor 2.1.0a2 on a FS-A1ST.

**Comment by Konamiman** [comment] 2019-01-24 15:21
I can't reproduce this. Could you please supply a blueMSX configuration to test?

By the way, DEVINFO displays information about Nextor drivers only, that's by design.

**Comment by Konamiman** [comment] 2020-07-12 09:58
I'm closing this since it's over one year old, I can't reproduce it and nobody else reported it. I'll reopen if you can provide further information.

**Closed as completed by Konamiman** 2020-07-12 09:58 UTC
Labels: bug, question
