### ISSUE TITLE
Cannot change volume name by command VOL - System file exists

### ISSUE THREAD

**Issue by mr-GreyWolf** [Konamiman/Nextor#57] opened 2020-06-03 11:06 UTC
Nextor kernel version 2.1.0 beta 2
NEXTOR.SYS version 2.10
COMMAND2.COM version 2.44

```
A:\> vol name_of_volume

*** System file exists
```
Discussion [here](https://www.msx.org/forum/msx-talk/software/vol-system-file-exists).

**Comment by sdsnatcher73** [comment] 2020-06-04 06:07
It has to do with Windows creating System Volume Information folder I think. This then gets a short name FAT entry and that is recognized as the “system file exists” and the volume showing as B (on my setup). I circumvented it by hsving Nextor on a floppy disk and after _fdisk and reboot I copy Nextor.sys and command2.com from floppy to SD, boot again and issue vol command (before modern OS touches the SD card)

**Comment by mr-GreyWolf** [comment] 2020-06-04 15:17
> It has to do with Windows creating System Volume Information folder I think.

I do not use Windows.
I copy additional files under Debian GNU/Linux.

**Comment by Konamiman** [comment] 2020-06-14 09:50
Hello, I'm unable to reproduce this. Could you please send me an image of the device giving you the error? If not, maybe a dump of the root directory area of the device could be useful.

**Comment by mr-GreyWolf** [comment] 2020-06-14 09:57
> Hello, I'm unable to reproduce this. Could you please send me an image of the device giving you the error? If not, maybe a dump of the root directory area of the device could be useful.

Hello!
How to create a dump of the root directory ?

**Comment by Konamiman** [comment] 2020-06-14 15:49
> How to create a dump of the root directory ?

Since you are using Linux, perhaps you could use the `dd` tool to dump the first few KBs of the device? (assuming that you are using the first/only partition of the device)

**Comment by mr-GreyWolf** [comment] 2020-06-18 08:55
@Konamiman, here's the [link](https://mega.nz/file/bjQlEIyT#lH7ZRr7ofsrxiGewuf5tCUkaVBl_WmD4X0D7037in8g) to dump of start first partition.

**Comment by Konamiman** [comment] 2020-06-19 09:34
Hello, thanks for the dump but it's not big enough. According to the boot sector parameters it seems that the size of the FAT is 64K, and since there are two FAT copies and the root directory size is 16K, I would need the first 145K of the partition (let's make it 150K to be safe).

**Comment by mr-GreyWolf** [comment] 2020-06-19 10:53
Hello, @Konamiman this [256K](https://mega.nz/file/K3ZxWAaa#1DZxanqm_HbUvsDiHCRW33fBa3GSpkFruEq3G4WfkT0) and [full partition image](https://mega.nz/file/auAn3YAZ#zfuTnKWJCzKy4HDzDR5du00x4V0lRUeAOhxR86ZBe-8).

**Comment by Konamiman** [comment] 2020-06-19 15:08
Ok, got it now. This will help me troubleshoot the issue, thank you!

**Comment by Konamiman** [comment] 2020-06-20 11:25
I can confirm that the issue is caused by the presence of long name entries in the root directory (those entries have an attributes byte of `0Fh`, which is volume label + system + hidden + read-only, so Nextor gets heavily confused with those). I'll include a fix in the next version of the Nextor kernel.

**Comment by Konamiman** [comment] 2020-08-01 11:34
Fixed in v2.1.0

**Closed as completed by Konamiman** 2020-08-01 11:34 UTC
Labels: bug, fixplemented

**Comment by MBilderbeek** [comment] 2020-12-27 18:50
I'm using 2.1.0 and I also ran into this issue... What can I do?

**Comment by Konamiman** [comment] 2020-12-27 19:18
@MBilderbeek are you using the latest 2.1.0 available (not an alpha or a beta)?

**Comment by MBilderbeek** [comment] 2020-12-27 19:20
Yes, I downloaded the 2.1.0 release version when I set up my CF card last week. Also flashed the accompanying IDE BIOS on my Carnivore 2.

**Comment by sdsnatcher73** [comment] 2020-12-27 19:55
It may be a similar but slightly different situation triggering the same issue. It’s wise to give the output of ver to make sure you are fully updated and if so I guess a dump of the partition will help in the investigation.

**Comment by MBilderbeek** [comment] 2020-12-27 20:11
Well, what can I tell.... I just tried it again and now it works...!? Nextor kernel version is (indeed) 2.1.0. Never mind, I guess...
