### ISSUE TITLE
If a driver implements the new DRV_CONFIG function, Nextor will panic with "No enough memory" if booted with CTRL+1

### ISSUE THREAD

**Issue by sdsnatcher** [Konamiman/Nextor#12] opened 2018-12-11 00:54 UTC
If, for the configuration index=0 the driver reports B=2 (requiring two drives) and the system is booted with CTRL+1 pressed, Nextor will panic with "No enough memory".

Tested with: Nextor 2.0.5-beta-1 on:
- Sanyo PHC-70FD with 512KB of internal Memory-Mapper
- Panasonic FS-A1ST with 1MB of internal Memory-Mapper
- Panasonic FS-A1ST with 256KB of internal Memory-Mapper

Steps to reproduce:

1) Modify an existing device-based driver so it reports B=2 when DRV_CONFIG is called with A=1
2) Boot your machine holding CTRL+1. According to [the documentation](https://www.konamiman.com/msx/nextor/docs/Nextor%202.0%20User%20Manual.pdf), this should force the DOS1-mode with a limit of 1 drive per interface

Result: Nextor will panic with a "No enough memory" message.

Suggested solution: As a measure of [software robustness](https://en.wikipedia.org/wiki/Robustness_(computer_science)), when CTRL is hold on boot, Nextor should limit the number of requested drives to at most 1, even if the driver asks for more drives on its DRV_CONFIG.

**Comment by Konamiman** [comment] 2019-01-19 21:36
I'm unable to reproduce this on blueMSX, tried emulating MSX2 and Turbo-R. Could you please try with blueMSX and tell me if you can find a configuration where this happens?

**Comment by Konamiman** [comment] 2020-07-12 09:57
I'm closing this since it's over one year old, I can't reproduce it and nobody else reported it. I'll reopen if you can provide further information.

**Closed as completed by Konamiman** 2020-07-12 09:57 UTC
Labels: bug, question
