### ISSUE TITLE
NEXTOR 2.1 Alpha-2 for Sunrise not  working on Toshiba HX-10DP

### ISSUE THREAD

**Issue by gdx-msx** [Konamiman/Nextor#32] opened 2019-08-09 01:05 UTC
NEXTOR 2.1 Alpha-2 for Sunrise ATA/IDE/CF doesn't work on a Toshiba HX-10DP. Slot management seems buggy. Original MSX-DOS2 v2.30 patched for MSX1 works perfectly. Even the version for ESE-RAM SCC of 512K (see link below works fine).
https://msx.org/downloads/esedos4m

With original Sunrise firmware the interface works on Toshiba HX-10DP (not perfectly but it's usable).

In addition, the second CF card is unusable on all my MSXs. When I use both cards at the same time, it corrupts the FAT.  (Tested in FAT16 only)

**Comment by Konamiman** [comment] 2022-07-13 15:46
Hi, is this issue still relevant? Does it still happen with the latest version of Nextor? And do you have other Nextor-powered (but non-IDE) hardware to test with?

**Comment by Konamiman** [comment] 2022-07-15 20:56
I'm unable to reproduce the issue on an emulator (blueMSX, MSX1 computer with the hx10dpbios.rom BIOS and Nextor with Sunrise IDE), could you please provide more details about your testing environment?

By the way about the data corruption, I assume your computer has an external RAM expansion, right? Otherwise, since the computer has only 64K RAM it will boot en DOS 1 mode, which doesn't support FAT16.

**Comment by Konamiman** [comment] 2023-10-26 15:28
I'm closing this but feel free to comment back if you can provide further information.

**Closed as completed by Konamiman** 2023-10-26 15:28 UTC
Labels: bug
