### ISSUE TITLE
_FDISK freezes if DEV_RW returns an error on its first call

### ISSUE THREAD

**Issue by sdsnatcher** [Konamiman/Nextor#5] opened 2018-11-25 13:21 UTC
As the title says, CALL FDISK freezes just after the device selection screen if DEV_RW returns an error on the first time it is called.

**Comment by Konamiman** [comment] 2019-01-20 17:23
What do you mean by "the first time it is called"? The absolute first time after system boot? Or the first time after FDISK starts? I have tested with a modified driver that always returns error on `DEV_RW`, but FDISK doesn't hang.

**Comment by Konamiman** [comment] 2020-07-12 09:58
I'm closing this since it's over one year old, I can't reproduce it and nobody else reported it. I'll reopen if you can provide further information.

**Closed as completed by Konamiman** 2020-07-12 09:58 UTC
Labels: bug, question
