### ISSUE TITLE
DOS1 mode DRV_CONFIG bug

### ISSUE THREAD

**Issue by sdsnatcher** [Konamiman/Nextor#15] opened 2018-12-17 01:00 UTC
This bug is probably related to the #12.

If the driver requests 2 drives on DRV_CONFIG with inputs A=1,B=0 (DOS2 mode), and requests only 1 drive for DRV_CONFIG with inputs A=1,B=1 (DOS1 mode), the DOS1 mode will allocate the drive letters to incorrect DEV/LUNs, as described ahead.

Tested on a Sanyo PHC-70FD.

Steps to reproduce:

1) Code a DRV_CONFIG to request 2 drive letters for the DOS2 mode, and only 1 drive letter to the DOS1 mode (to save memory in this mode)
2) Use an MSX that has an internal drive, and connect a Nextor cartridge that has 2 drives (like an IDE with 2 CF cards). All drives must have FAT12-formated medias inside.
3) Boot the MSX and keep the "1" key pressed to force the DOS1 mode
4) On the BASIC prompt, type FILES"B:"
Result-1: The files from the CF card-2 will be shown. But this DEV/LUN should have been canceled, and the files from the floppy drive should have been listed.
5) On the BASIC prompt, type FILES"C:"
Result-2: A "Disk I/O error" will occur. But the drive "C:" should have been mapped to the ghost drive of the floppy interface.

**Comment by Konamiman** [comment] 2019-01-20 16:04
I'm sorry but I'm not able to reproduce this. I'm using blueMSX, emulating Sunrise IDE with two devices holding each a FAT12 partition. If I modify DRV_CONFIG as instructed and boot in DOS1 mode, that's what `CALL DRVINFO` gives me:

![image](https://user-images.githubusercontent.com/937723/51441766-3982dc80-1cd5-11e9-9ff6-97b939ab6acd.png)

And if I boot in normal mode:

![image](https://user-images.githubusercontent.com/937723/51441777-6800b780-1cd5-11e9-83bf-6a6ce3d3a3a0.png)

So it works as expected. What is `CALL DRVINFO` giving you?

**Comment by Konamiman** [comment] 2020-07-12 09:58
I'm closing this since it's over one year old, I can't reproduce it and nobody else reported it. I'll reopen if you can provide further information.

**Closed as completed by Konamiman** 2020-07-12 09:58 UTC
Labels: bug, question
