### ISSUE TITLE
It fails after loading Nextor.SYS on MSX without disk drives.

### ISSUE THREAD

**Issue by Aquijacks** [Konamiman/Nextor#27] opened 2019-02-10 21:52 UTC
In compilations Sunride gives failure due to corruption of RAM after loading NEXTOR.SYS in MSX (All versions) that do not have an internal disk drive.
In my case, when compiling for Flashjacks unit the error only occurred in MSX without internal floppy disk. I suspect that they do not work in the IDE (Carnivore, etc ...) but the failure could be extended to all versions of devices.

**Comment by Wierzbowsky** [comment] 2019-02-12 14:01
Probably the same reason why it doesn't work with Carnivore2 on diskless machines.

**Comment by Konamiman** [comment] 2019-02-26 21:58
I can't reproduce this on blueMSX emulating Sunrise IDE. Anyway, you mention corruption of RAM - can you please provide more details?

**Comment by Konamiman** [comment] 2019-04-29 14:37
Fixed in v2.1.0 beta 2

**Closed as completed by Konamiman** 2019-04-29 14:37 UTC
Labels: bug, fixplemented
