### ISSUE TITLE
DOS1 mode reports "Disk I/O error" instead of "Disk offline" before any media is inserted

### ISSUE THREAD

**Issue by sdsnatcher** [Konamiman/Nextor#13] opened 2018-12-16 18:48 UTC
Tested on Nextor 2.0.5-beta1

Before any media is inserted, DOS1 on BASIC will report "Disk I/O error" instead of "Disk offline".

Steps to reproduce:

1) Boot the MSX without any media on the drive while holding the "1" key, to force the DOS1 mode
2) Type the command FILES on the BASIC prompt
- LUN_INFO will be called 3 times. (*1)
Result-1: The error "Disk I/O error" will be reported instead of "Disk offline" like a normal floppy drive interface does.
Note: You might repeat step-2 as much as you want

3) Insert a media in the drive and type FILES
- LUN_INFO will be called, and DEV_DW will be called to read the directory. The files will be shown.

4) Remove the media from the drive and type FILES
- Result-2: Now The "Disk offline" will be shown whenever needed
Note: LUN_INFO won't be called ever again, even after media changes

*1:  It doesn't make any difference if LUN_INFO reports a missing media by returning A=1 (LUN not available), or A=0 with the unknown fields set to zero (meaning not available).

**Comment by Konamiman** [comment] 2023-10-26 15:34
Hi, I'm unable to reproduce this in Nextor 2.1.1. Since you report that you tested on Nextor 2.0.5, I'll assume that the issue is fixed by now. Please feel free to comment back if you are still able to reproduce the issue when using the latest Nextor kernel version.

**Closed as completed by Konamiman** 2023-10-26 15:34 UTC
Labels: bug
